### ISSUE TITLE
Icon issue.

### ISSUE THREAD

**Issue by Tux8068** [Tux8068/rgb-editor#5]
The icon of the project works when you're running it in intellij, but doesn't appear in the jar format.
(lines 30 & 35.)

# When running in IDE
![image](https://user-images.githubusercontent.com/65930745/145733041-7baeff7a-084d-4d65-aff6-38f2592f3ff1.png)

# When running from JAR
![image](https://user-images.githubusercontent.com/65930745/145733064-1dab9371-611f-488c-8384-67b0272026f8.png)

**Comment by Kami147** [comment]
You need to export the resources folder with the gradle project, this can be done via the config file, see [this](https://stackoverflow.com/questions/24724383/add-resources-config-files-to-your-jar-using-gradle) for more info

**Comment by Kami147** [comment]
Should be fixed in #9
